//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFarkWebSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Yonetici_id { get; set; }
        public string Yonetici_ad { get; set; }
        public string Yonetici_sifre { get; set; }
    }
}
