//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFarkWebSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarkındalıkHastalıgı
    {
        public short FHastalik_id { get; set; }
        public string FHastalik_Kod { get; set; }
        public string FHastalik_Bilgi { get; set; }
        public System.DateTime FHastalik_Tarih { get; set; }
    }
}
