//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFarkWebSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class İletisim
    {
        public short İletisim_id { get; set; }
        public string İletisim_konusu { get; set; }
        public string İletisim_icerik { get; set; }
        public string İletisim_sahip { get; set; }
    }
}
