//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFarkWebSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kalıtsal_Hastalık
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kalıtsal_Hastalık()
        {
            this.yorumlar = new HashSet<yorumlar>();
        }
    
        public int KHastalik_id { get; set; }
        public string KHastalik_ad { get; set; }
        public string KHastalik_bilgi { get; set; }
        public string KHastalik_foto { get; set; }
        public System.DateTime KHastalik_tarih { get; set; }
        public short Kategori_id { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorumlar> yorumlar { get; set; }
    }
}
