//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFarkWebSite.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class genfarkEntities : DbContext
    {
        public genfarkEntities()
            : base("name=genfarkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<FarkındalıkHastalıgı> FarkındalıkHastalıgı { get; set; }
        public virtual DbSet<İletisim> İletisim { get; set; }
        public virtual DbSet<Kalıtsal_Hastalık> Kalıtsal_Hastalık { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<yorumlar> yorumlar { get; set; }
    }
}
