//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFarkWebSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorumRaporu
    {
        public string KHastalik_ad { get; set; }
        public string Yorum_ad { get; set; }
        public string Yorum_soyad { get; set; }
        public System.DateTime Yorum_tarih { get; set; }
    }
}
