//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFarkWebSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorumlar
    {
        public int Yorum_id { get; set; }
        public string Yorum_ad { get; set; }
        public string Yorum_soyad { get; set; }
        public string Yorum_mail { get; set; }
        public System.DateTime Yorum_tarih { get; set; }
        public bool Yorum_onay { get; set; }
        public string Yorum_icerik { get; set; }
        public int KHastalik_id { get; set; }
    
        public virtual Kalıtsal_Hastalık Kalıtsal_Hastalık { get; set; }
    }
}
